config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  get 'dashboard/index'
  get 'requisitions/print'

  get 'requisitions/get_iso_list'

  resources :requisitions do
    resources :spools do
      get 'delete'
    end
  end
  

  resources :settings #, only: [:index, :update, :create]
  resources :rules
 

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  	@iso = Material.select(:isometric_number).distinct.order(isometric_number: :asc)
  	@types = Type.all
  	@requisition = Requisition.new
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<div class="container">
	<div class="col-sm-3">&nbsp;</div>
	<div class="col-sm-6">
		<%= form_tag(new_requisition_path, method: 'get', class: 'iso_select_form') do %>
		<%#= form_for :requisition, url: new_requisition_path, method: 'get' do |f| %>
			<!-- <div class="form-group">
				<label form="isoSearch">ISO</label>
				<%#= collection_select(nil, :isometric_number, @iso, :isometric_number, :isometric_number, {}, class: 'form-control' ) %>
			</div> -->
			<div class="form-group" id="_isometric_numberDiv">
				<label class="control-label">ISO</label>
				<%= text_field nil, :isometric_number, class: 'form-control' %>
				<span id="isoHelp" class="help-block">Start typing the ISO number and the list will appear</span>
			</div>
			<div class="form-group">
				<label form="typeSearch">Component Type</label>
				<%= collection_select(nil, :type_id, @types, :id, :name, {include_blank: 'All Types'}, class: 'form-control') %>
			</div>
			<button type="submit" class="btn btn-primary pull-right" id="search">Create</button>
		<% end %>
	</div>
	<div class="col-sm-3">&nbsp;</div>
</div>

<script>

	$(document).ready(function() {
		$("#_isometric_number").autocomplete({
			source: function( request, response ) {
	        $.ajax({
	          url: "/requisitions/get_iso_list",
	          dataType: "json",
	          data: {
	            term: request.term
	          },
	          success: function( data ) {
	            response( $.map( data, function( iso ) {
                    return {
                        label: iso.isometric_number
                    }
                }));
	          }
	        });
	      },
	      minLength: 1
		})

		var requiredFields = ['_isometric_number'];

		$(".iso_select_form").submit(function() {
			if (validateform()) {
	          return true;
	        } else { return false; } 
		});

		function validateform() {
			var bValid = true;      
			jQuery.each ( requiredFields, function (i, val) {
				if ($("#" + val).prop('type') == "text" || $("#" + val).prop('type') == "textarea") {
					if ($("#" + val).val() == "") {
					$("#" + val + "Div").addClass("has-error");
					bValid = false;
				} else { 
					$("#" + val + "Div").removeClass("has-error");
				};
		    	} else if ($("#" + val).prop('type') == "checkbox") {
					if ($("#" + val).prop("checked") == false) {
						$("#" + val + "Div").addClass("has-error");
			        	bValid = false;
					} else { 
						$("#" + val + "Div").removeClass("has-error");
					};
				};
			});

		  	return bValid;
		};

	});

</script>