config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  get 'dashboard/index'
  get 'requisitions/print'

  get 'requisitions/get_iso_list'

  resources :requisitions do
    resources :spools do
      get 'delete'
    end
  end
  

  resources :settings #, only: [:index, :update, :create]
  resources :rules
 

end

app/models/requisition.rb
class Requisition < ActiveRecord::Base
	has_many :materials

	accepts_nested_attributes_for :materials,
    :reject_if => :all_blank
end

app/controllers/requisitions_controller.rb
class RequisitionsController < ApplicationController
	def index

	end

	def get_iso_list
		@isos = Material.select(:isometric_number).distinct.where("lower(isometric_number) LIKE ?", "#{params[:term].downcase}%").order(isometric_number: :asc)
		respond_to do |format|
			format.json { render json: @isos }
		end
	end

	def show
		@requisitions = Requisition.where(isometric_number: params[:id])
	end

	def new
		# Requisition Number Generator
		# ISO Number + Sheet No + Seq. Number
		# ie) 00001A + A01 (Change A to S) + XX
	
		@isometric_number = params[:isometric_number].strip
		@types = Type.all

		@requisition = Requisition.where(isometric_number: @isometric_number).take

		# Check if @requistion is empty or not
		if @requisition.blank?
			@requisition = Requisition.new			
		end

		# Maybe split things up like this to accomodate the different types?

		# @spool_material = ""
		# @support_material = ""
		# @loose_items = ""

		if params[:type_id] == ''
			@types = Type.all

			# @spool_material = ""
			# @support_material = ""
			# @loose_items = ""
		else
			@types = Type.where(id: params[:type_id])
		end

		# ID_Prefabrication V = Prefab (Spools) - M = Field Material
		@materials = Material.where(isometric_number: @isometric_number, id_prefabrication: 'M')
		#@sheets = Material.where(isometric_number: @isometric_number, id_prefabrication: 'M').select('DISTINCT spool')
		@sheets = Material.select(:isometric_number, :spool).distinct.where(isometric_number: @isometric_number, id_prefabrication: 'M').order(:spool)

		@find_materials = @materials.select{|mat| mat.material_type === 3}
	end

	def create
		#Temporary - Need to pass the type_id if only 1 type selected.
		@types = Type.all

		# if params[:type_id] == ''
		# 	@types = Type.all
		# else
		# 	@types = Type.where(id: params[:type_id])
		# end

		@settings = Setting.find(1)

		@materials = Material.where(isometric_number: params[:requisition][:isometric_number], id_prefabrication: 'M')

		@types.each do |t|
			@materials_by_type = @materials.select{|m| m.material_type === t.id}
			
			# Update material with req id.
			row = @settings.row_max

			@materials_by_type.each do |m|			
				if row === @settings.row_max
					@requisition = Requisition.create(requisition_params)
					@requisition.type_id = t.id
					@requisition.save
					row = 0
				end

				m.requisition_id = @requisition.id
				m.save
				row += 1
			end
		end

		@requisitions = Requisition.where(isometric_number: params[:requisition][:isometric_number]).order(type_id: :asc, materials_count: :desc)
	end

	def update
		#Temporary - Need to pass the type_id if only 1 type selected.
		@types = Type.all
		# if params[:type_id] == ''
		# 	@types = Type.all
		# else
		# 	@types = Type.where(id: params[:type_id])
		# end

		@requisitions = Requisition.where(isometric_number: params[:requisition][:isometric_number])
		@materials = Material.where(isometric_number: params[:requisition][:isometric_number], id_prefabrication: 'M', requisition_id: nil)

		@settings = Setting.find(1)

		@types.each do |t|

			@requisition_list = Requisition.where(isometric_number: params[:requisition][:isometric_number], type_id: t.id).order(materials_count: :desc)

			@materials_by_type = @materials.select{|m| m.material_type === t.id}

			if @requisition_list.empty?
				# If there is currently no Req. Created.	
			
				# Update material with req id.
				row = @settings.row_max

				@materials_by_type.each do |m|			
					if row === @settings.row_max
						@requisition = Requisition.create(requisition_params)
						@requisition.type_id = t.id
						@requisition.save
						row = 0
					end

					m.requisition_id = @requisition.id
					m.save
					row += 1
				end
			else
				# Req Exists.
				@requisition_list.each do |r|
					r.update_attributes(requisition_params)

					# Check if current Req. has reached max_rows, if not, add material to that req.
					row = r.materials.count #@materials_by_type.count
					req_id = r.id

					@materials_by_type.each do |m|
						if row === @settings.row_max
							requisition = Requisition.create(requisition_params)
							requisition.type_id = r.type_id
							requisition.save
							row = 0
							req_id = requisition.id
						end

						m.requisition_id = req_id
						m.save
						row += 1
					end
				end
			end
		end

		# Display requisitions in order by Type, Spool = 1, Supports = 2, Loose Items = 3 also show the reqs with the most items first.
		@requisitions = Requisition.where(isometric_number: params[:requisition][:isometric_number]).order(type_id: :asc, materials_count: :desc)
	end

	private
		def requisition_params
			params.require(:requisition).permit(:project, :date, :work_package_number, :intended_use, :requested_by, :delivery_location, :isometric_number, :type_id)
		end
end

app/helpers/requisition_helper.rb
module RequisitionHelper
end

app/helpers/requisitions_helper.rb
module RequisitionsHelper
end

app/views/requisitions/_form.html.erb
<%= form_for @requisition do |f| %>
	<div class="panel panel-default">
		<div class="panel-body">
			<div class="col-sm-12">
				<div class="col-sm-12">
					<h4>ISO: <b><%= @isometric_number %></b></h4>
					<%= f.hidden_field :isometric_number, value: @isometric_number %>
				</div>
				<div class="form-group col-sm-4">
					<label for="requisition_project" class="control-label">Project</label>
					<%= f.text_field :project, class: 'form-control' %>
				</div>
				<div class="form-group col-sm-4">
					<label for="requisition_date" class="control-label">Date</label>
					<div class="input-group date" id="requisition_date" data-date="<%=DateTime.now%>">
						<%= f.text_field :date, class: 'form-control req_date', readonly: true, value: DateTime.now.strftime("%d/%m/%Y") %>
						<span class="input-group-addon add-on">
			              <span class="glyphicon glyphicon-calendar" aria-hidden="true"></span>
			            </span>
					</div>
				</div>
				<div class="form-group col-sm-4">
					<label for="requisition_work_package_number" class="control-label">Work Package Number</label>
					<%= f.text_field :work_package_number, class: 'form-control' %>
				</div>
				<div class="form-group col-sm-12">
					<label for="requisition_intended_use" class="control-label">Intended Use</label>
					<%= f.text_field :intended_use, class: 'form-control' %>
				</div>

				<div class="form-group col-sm-6">
					<label for="requisition_requested_by" class="control-label">Requested By</label>
					<%= f.text_field :requested_by, class: 'form-control' %>
				</div>

				<div class="form-group col-sm-6">
					<label for="requisition_delivery_location" class="control-label">Delivery Location</label>
					<%= f.text_field :delivery_location, class: 'form-control' %>
				</div>
			</div>
		</div>
	</div>
	<div id="materiallist">
		<%= render 'materials' %>
	</div>
	<div class="col-sm-12">
		<div class="row">
			<%= f.submit 'Generate', class: 'btn btn-primary pull-right' %>
		</div>
	</div>
<% end %>

<div id="spool-modal" class="modal fade add-spool" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

<script>
	$(document).ready(function() {
		var nowTemp = new Date();
	    var now = new Date(nowTemp.getFullYear(), nowTemp.getMonth(), nowTemp.getDate(), 0, 0, 0, 0);
	    
	    $('#requisition_date').datepicker({
	      format: 'mm/dd/yyyy',
	      onRender: function(date) {
	      return date.valueOf() < now.valueOf() ? 'disabled' : '';
	    }}).on('changeDate', function(ev){
	      $('#requisition_date').datepicker('hide');
	    });
	});
</script>

app/views/requisitions/_materials.html.erb
<!-- NEED TO HIDE WHEN NO ITEMS EXIST -->
<div class="panel panel-danger">
	<div class="panel-heading">
		<h4><b>Unknown Items</b> <small>Create rules for these items to be identified correctly</small></h4>
	</div>
	<div class="panel-body">
		<div class="col-sm-12">
			<div class="table-responsive">
				<table class="table">
					<thead>
						<tr>
							<th class="text-center">Quantity</th>
							<th>Material Description</th>
							<th class="text-center">MMS Part No.</th>
							<th class="text-center">Drawing No.</th>
							<th class="text-center">Work Package No.</th>
							<th class="text-center">Tag No.</th>
							<th></th>
						</tr>
					</thead>
					<tbody>
						<% @materials.each do |m| %>
							<% if m.material_type === "" %>
							<tr>
								<td class="text-center"><%= m.quantity %></td>
								<td><%= m.requisition_description %></td>
								<td class="text-center"><%= m.component_number %></td>
								<td class="text-center"><%= m.isometric_number %>-<%= m.sheet_no%></td>
								<td class="text-center"></td>
								<td class="text-center"></td>
								<td class="text-center">
									<%= link_to new_rule_path(desc: m.requisition_description), remote: true, class: "btn btn-default btn-xs" do %>
										<span class="glyphicon glyphicon-export" title="Create Rule"></span>
									<% end %>
								</td>
							</tr>
							<% end %>
						<% end %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<% @types.each do |t| %>
	<div class="panel panel-default">
		<div class="panel-body">
			<div class="col-sm-12">
				<div class="col-sm-6">
					<h4>Component Type: <b><%= t.name %></b></h4>
				</div>
				<div class="col-sm-12">
					<div class="table-responsive">
						<table class="table" id="<%=t.name%>List">
							<thead>
								<tr>
									<th class="text-center">Quantity</th>
									<th>Material Description</th>
									<th class="text-center">MMS Part No.</th>
									<th class="text-center">Drawing No.</th>
									<th class="text-center">Work Package No.</th>
									<th class="text-center">Tag No.</th>
									<% if t.name === "Spool" %>
										<th></th>
									<% end %>
								</tr>
							</thead>
							<tbody>
								<% @materials.each do |m| %>
									<% if m.material_type === t.id %>
									<tr>
										<td class="text-center"><%= m.quantity %></td>
										<td><%= m.requisition_description %></td>
										<td class="text-center"><%= m.component_number %></td>
										<td class="text-center"><%= m.isometric_number %>-<%= m.sheet_no%></td>
										<td class="text-center"></td>
										<td class="text-center"></td>
										<% if t.name === "Spool" %>
											<td class="text-center">
												<%= link_to 'Edit', edit_requisition_spool_path(m.isometric_number, m.id), remote: true, class: "btn btn-primary btn-xs" %>
												<%= link_to 'Delete', requisition_spool_delete_path(m.isometric_number, m.id), remote: true, class: "btn btn-danger btn-xs" %>	
											</td>
										<% end %>
									</tr>
									<% end %>
								<% end %>
							</tbody>
						</table>
					</div>
				</div>
				<div class="col-sm-12">
					<% if t.name === "Spool" %>
						<%= link_to 'Add Spool', new_requisition_spool_path(@isometric_number), remote: true, class: "btn btn-primary pull-right" %>
						<!-- <button class="btn btn-success pull-right" type="button" data-toggle="modal" data-target=".add-spool">Add Spool</button> -->
					<% end %>
				</div>
			</div>
		</div>
	</div>
<% end %>

<script>

	$(document).ready(function() {

		function getUniqueId() {
			var d1 = new Date();
	        return (d1.getTime()-d1.getMilliseconds())/1000;
	    };

	    var counter = getUniqueId();

		function addNewSpool() {
			var spoolCount = counter;
			$("#SpoolList tr:last").after(
				'<tr id="spool' + counter + '">' + 
					'<td class="text-center">1</td>' +
					'<td>' + $("#spoolDescription").val() + '</td>' +
					'<td class="text-center"></td>' +
					'<td class="text-center">' + $("#spoolDrawing option:selected").text() + '</td>' +
					'<td class="text-center"></td>' +
					'<td class="text-center"></td>' +
				'</tr>' + 
				'<input type="hidden" id="material_' + counter + '_designation" name="material[' + counter + '][designation]" value="' + $("#spoolDescription").val() + '">' +
				'<input type="hidden" id="material_' + counter + '_spool" name="material[' + counter + '][spool]" value="' + $("#spoolDrawing").val() + '">' +
				'<input type="hidden" id="material_' + counter + '_isometric_number" name="material[' + counter + '][isometric_number]" value="<%= @isometric_number %>">'
			);

			counter++;
			
			// Clear Textbox
			$("#spoolDescription").val('');
			// Close Dialog
			$("#spool-modal").modal("hide")

		};

		function removeSpool() {

		};

		function editSpool() {

		};

		$("#btnAddSpool").click(function () {
	        addNewSpool();
	    });

	});

</script>

app/views/requisitions/_printable.html.erb
<% @requisitions.each do |r| %>
	<div class="container" id="requisition">
		<div class="panel panel-default" id="requisition-panel">
			<div class="panel-body">
				<div class="col-xs-12 col-sm-12">
					<div class="row">
						<div class="col-xs-12 col-sm-12">
							<div class="col-xs-3 col-sm-3">
								<% if Setting.find(1).logo.present? %>
									<%= image_tag Setting.find(1).logo.url(:print) %> 
								<% end %>
							</div>
							<div class="col-xs-6 col-sm-6 text-center">
								<h3>WAREHOUSE REQUEST FOR ISSUE</h3>
							</div>
							<div class="col-xs-3 col-sm-3">
								<p>Project: <b><%= r.project %></b></p>
								<p>WRFI No: <b><%=@settings.wrfi_prefix %><%= r.id.to_s.rjust(5, '0') %></b></p>
								<p>Date: <b><%= r.date %></b></p>
								<p>Work Package No: <b><%= r.work_package_number %></b></p>
							</div>
						</div>
					</div>
					<div class="col-xs-12 col-sm-12" style="padding-top: 10px;">
						<p>Intended Use: <b><%= r.intended_use %></b></p>
					</div>

					<div class="col-xs-6 col-sm-6">
						<p>Requested By: <b><%= r.requested_by %></b></p>
					</div>

					<div class="col-xs-6 col-sm-6">
						<p>Delivery Location: <b><%= r.delivery_location %></b></p>
					</div>
					<div class="col-xs-12 col-sm-12">
						<div class="row">
							<div class="col-sm-12">
								<div class="table-responsive">
									<table class="table table-bordered table-condensed">
										<thead>
											<tr>
												<th class="text-center">Qty</th>
												<th class="text-center">Req</th>
												<th class="text-center">Ship</th>
												<th>Material Description</th>
												<th class="text-center">MMS Part No.</th>
												<th class="text-center">Drawing No.</th>
												<th class="text-center">Work Package No.</th>
												<th class="text-center">Tag No.</th>
											</tr>
										</thead>
										<tbody>
											<% r.materials.order("spool asc").each do |m| %>
												<%# if m.material_type === t.id %>
												<tr>
													<td class="text-center"><%= m.quantity %></td>
													<td class="text-center"></td>
													<td clas="text-center"></td>
													<td><%= m.requisition_description %></td>
													<td class="text-center"><%= m.component_number %></td>
													<td class="text-center"><%= m.isometric_number %>-<%= m.sheet_no%></td>
													<td class="text-center"></td>
													<td class="text-center"></td>
												</tr>
												<% #end %>
											<% end %>
											<% (1..@settings.row_max-r.materials.count).each do |line| %>
												<tr>
													<td class="text-center">&nbsp;</td>
													<td class="text-center">&nbsp;</td>
													<td class="text-center">&nbsp;</td>
													<td>&nbsp;</td>
													<td class="text-center">&nbsp;</td>
													<td class="text-center">&nbsp;</td>
													<td class="text-center">&nbsp;</td>
													<td class="text-center">&nbsp;</td>
												</tr>
											<% end %>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-xs-12 col-sm-12">
							<div class="col-xs-4 col-sm-4">
								<p style="border-bottom: 1px solid #000000">Received By:</p>
							</div>
							<div class="col-xs-2 col-sm-2">
								<p style="border-bottom: 1px solid #000000">Date:</p>
							</div>
							<div class="col-xs-4 col-sm-4">
								<p style="border-bottom: 1px solid #000000">Issued By:</p>
							</div>
							<div class="col-xs-2 col-sm-2">
								<p style="border-bottom: 1px solid #000000">Date:</p>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<footer></footer>
<% end %>

app/views/requisitions/create.html.erb
<%= render 'printable' %>

app/views/requisitions/index.html.erb
<div class="container">
	<form>
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="col-sm-12">
					<div class="col-sm-12">
						<h4>ISO: <b>20502A - Sheet 1</b></h4>
					</div>
					<div class="form-group col-sm-4">
						<label for="project" class="control-label">Project</label>
						<input type="text" class="form-control">
					</div>
					<div class="form-group col-sm-4">
						<label for="project" class="control-label">Date</label>
						<input type="text" class="form-control">
					</div>
					<div class="form-group col-sm-12">
						<label for="intendeduse" class="control-label">Intended Use</label>
						<input type="text" class="form-control">
					</div>

					<div class="form-group col-sm-6">
						<label for="requestedby" class="control-label">Requested By</label>
						<input type="text" class="form-control">	
					</div>

					<div class="form-group col-sm-6">
						<label for="requestedby" class="control-label">Delivery Location</label>
						<input type="text" class="form-control">
					</div>
				</div>
			</div>
		</div>
		<div class="panel panel-default">
			<div class="panel-body">
				<div class="col-sm-12">
					<div class="col-sm-6">
						<h4>Component Type: <b>Spools</b></h4>
					</div>
					<div class="col-sm-6">
						<h4 class="pull-right">WRFI No: <b>10842</b></h4>
					</div>
					<div class="col-sm-12">
						<div class="table-responsive">
							<table class="table">
								<thead>
									<tr>
										<th class="text-center">Quantity</th>
										<th class="text-center">Required</th>
										<th>Material Description</th>
										<th class="text-center">MMS Part Number</th>
										<th class="text-center">Drawing Number</th>
										<th class="text-center">Work Package Number</th>
										<th class="text-center">Tag Number</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td class="text-center">1</td>
										<td>
											<div class="form-group">
												<input type="text" class="form-control">
											</div>
										</td>
										<td>STMH0Z-20502A-KE59CAL-1</td>
										<td class="text-center"></td>
										<td class="text-center">20502A 1 of 4</td>
										<td class="text-center"></td>
										<td class="text-center"></td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>				
				</div>
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-body">
				<div class="col-sm-12">
					<div class="col-sm-6">
						<h4>Component Type: <b>Supports</b></h4>
					</div>
					<div class="col-sm-6">
						<h4 class="pull-right">WRFI No: <b>10843</b></h4>
					</div>
					<div class="col-sm-12">
						<div class="table-responsive">
							<table class="table">
								<thead>
									<tr>
										<th class="text-center">Quantity</th>
										<th>Material Description</th>
										<th class="text-center">MMS Part Number</th>
										<th class="text-center">Drawing Number</th>
										<th class="text-center">Work Package Number</th>
										<th class="text-center">Tag Number</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td class="text-center">1</td>
										<td>SPECIAL SUPPORT</td>
										<td class="text-center">CP20502A-02</td>
										<td class="text-center">20502A 1 of 4</td>
										<td class="text-center"></td>
										<td class="text-center"></td>
									</tr>
									<tr>
										<td class="text-center">1</td>
										<td>8,0 PTFE GUIDE</td>
										<td class="text-center">CS0036-08</td>
										<td class="text-center">20502A 1 of 4</td>
										<td class="text-center"></td>
										<td class="text-center"></td>
									</tr>
									<tr>
										<td class="text-center">1</td>
										<td>350,0 210,0 PIPE SHOE, LOOSE POINT</td>
										<td class="text-center">CS4108-03</td>
										<td class="text-center">20502A 1 of 4</td>
										<td class="text-center"></td>
										<td class="text-center"></td>
									</tr>
									<tr>
										<td class="text-center">1</td>
										<td>1/2" EI Component</td>
										<td class="text-center">20PT1705A</td>
										<td class="text-center">20502A 1 of 4</td>
										<td class="text-center"></td>
										<td class="text-center"></td>
									</tr>
									<tr>
										<td class="text-center">1</td>
										<td>1/2" EI Component</td>
										<td class="text-center">20PT1705B</td>
										<td class="text-center">20502A 1 of 4</td>
										<td class="text-center"></td>
										<td class="text-center"></td>
									</tr>
									<tr>
										<td class="text-center">1</td>
										<td>1/2" EI Component</td>
										<td class="text-center">20PT1705C</td>
										<td class="text-center">20502A 1 of 4</td>
										<td class="text-center"></td>
										<td class="text-center"></td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>				
				</div>
			</div>
		</div>

		<div class="panel panel-default">
			<div class="panel-body">
				<div class="col-sm-12">
					<div class="col-sm-6">
						<h4>Component Type: <b>Loose Piping Items</b></h4>
					</div>
					<div class="col-sm-6">
						<h4 class="pull-right">WRFI No: <b>10844</b></h4>
					</div>
					<div class="col-sm-12">
						<div class="table-responsive">
							<table class="table">
								<thead>
									<tr>
										<th class="text-center">Quantity</th>
										<th>Material Description</th>
										<th class="text-center">MMS Part Number</th>
										<th class="text-center">Drawing Number</th>
										<th class="text-center">Work Package Number</th>
										<th class="text-center">Tag Number</th>
									</tr>
								</thead>
								<tbody>
									<tr>
										<td class="text-center">3</td>
										<td>3/4" BLIND FLANGE W. 1/2" NPT HOLE</td>
										<td class="text-center">FBC1630AI</td>
										<td class="text-center">20502A 1 of 4</td>
										<td class="text-center"></td>
										<td class="text-center"></td>
									</tr>
									<tr>
										<td class="text-center">3</td>
										<td>3/4" GATE VALVE, SMALL SIZES</td>
										<td class="text-center">SKXI-03-FEGA</td>
										<td class="text-center">20502A 1 of 4</td>
										<td class="text-center"></td>
										<td class="text-center"></td>
									</tr>
									<tr>
										<td class="text-center">12</td>
										<td>5/8" STUD BOLT / NUTS</td>
										<td class="text-center">BB---02-BEAA</td>
										<td class="text-center">20502A 1 of 4</td>
										<td class="text-center"></td>
										<td class="text-center"></td>
									</tr>
									<tr>
										<td class="text-center">16</td>
										<td>1 1/4" STUD BOLT / NUTS</td>
										<td class="text-center">BB---02-BEAA</td>
										<td class="text-center">20502A 1 of 4</td>
										<td class="text-center"></td>
										<td class="text-center"></td>
									</tr>
									<tr>
										<td class="text-center">1</td>
										<td>10" SPIRAL WOUND GASKET</td>
										<td class="text-center">DSBH-02-GACA</td>
										<td class="text-center">20502A 1 of 4</td>
										<td class="text-center"></td>
										<td class="text-center"></td>
									</tr>
									<tr>
										<td class="text-center">3</td>
										<td>3/4" SPIRAL WOUND GASKET</td>
										<td class="text-center">DSBH-02-GACA</td>
										<td class="text-center">20502A 1 of 4</td>
										<td class="text-center"></td>
										<td class="text-center"></td>
									</tr>
								</tbody>
							</table>
						</div>
					</div>
				</div>
			</div>
		</div>
		<div class="col-sm-12">
			<div class="row">
				<button type="button" id="generate" class="btn btn-primary pull-right">Generate</button>
			</div>
		</div>
	</form>
</div>


<script>

$('#generate').click(function() {
	window.location.href= window.location + "/show";
});

</script>

app/views/requisitions/new.html.erb
<div class="container">
	<%= render 'form' %>
</div>

<div id="rule-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

<script>

</script>

app/views/requisitions/update.html.erb
<%= render 'printable' %>