config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  get 'dashboard/index'
  get 'requisitions/print'

  get 'requisitions/get_iso_list'

  resources :requisitions do
    resources :spools do
      get 'delete'
    end
  end
  

  resources :settings #, only: [:index, :update, :create]
  resources :rules
 

end

app/controllers/spools_controller.rb
class SpoolsController < ApplicationController
	def index

	end

	def new
		@isometric_number = params[:requisition_id]
		@material = Material.new
		
		@sheets = Material.select(:isometric_number, :spool).distinct.where(isometric_number: @isometric_number, id_prefabrication: 'M').order(:spool)
	end

	def create
		@material = Material.create(isometric_number: params[:requisition_id], spool: params[:material][:spool], quantity: 1, designation: params[:material][:designation], type_id: 1, id_prefabrication: 'M')
		@materials = Material.where(isometric_number: params[:requisition_id], id_prefabrication: 'M')
		@isometric_number = params[:requisition_id]
		@types = Type.all
	end

	def edit
		@isometric_number = params[:requisition_id]
		@material = Material.find(params[:id])

		@sheets = Material.select(:isometric_number, :spool).distinct.where(isometric_number: @isometric_number, id_prefabrication: 'M').order(:spool)
	end

	def update
		@materials = Material.where(isometric_number: params[:requisition_id], id_prefabrication: 'M')
		
		@material = Material.find(params[:id])
		@material.designation = params[:material][:designation]
		@material.spool = params[:material][:spool]
		@material.save
		
		@isometric_number = params[:requisition_id]
		@types = Type.all
	end

	def delete
		@material = Material.find(params[:spool_id])
	end

	def destroy
		@material = Material.find(params[:id])
		@material.destroy
		@materials = Material.where(isometric_number: params[:requisition_id], id_prefabrication: 'M')
		@isometric_number = params[:requisition_id]
		@types = Type.all
	end
end

#(isometric_number: v[:isometric_number], spool: v[:spool], quantity: 1, designation: v[:designation], type_id: 1, id_prefabrication: 'M')

app/helpers/spools_helper.rb
module SpoolsHelper
end

app/views/spools/_delete.html.erb
<div class="modal-dialog modal-sm">
    <div class="modal-content">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
			<h4 class="modal-title" id="myModalLabel">Delete Spool</h4>
		</div>
		<div class="modal-body">
			<ul class="errors"></ul>
			Are you sure you want to delete <b><%= @material.designation %></b>?
		</div>	
     	<div class="modal-footer">
  		  <%= link_to "No", "#", class: "btn btn-primary", data: { dismiss: "modal" } %>
  		  <%= link_to "Yes", requisition_spool_path(@material.isometric_number, @material), method: :delete, remote: true, class: "btn btn-danger" %>
		</div>
	</div>
</div>

app/views/spools/_edit.html.erb
<div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Edit Spool</h4>
      </div>
      <%= form_for @material, url: requisition_spool_path(@isometric_number, @material), method: :put, remote: true do |f| %>
			<div class="modal-body">				
				<div class="form-group" id="material_designationDiv">
					<label for="" class="control-label">Description</label>
					<%= f.text_field :designation, class: 'form-control' %>
					<!-- <input type="text" class="form-control" id="spoolDescription"> -->
				</div>
				<div class="form-group" id="material_spoolDiv">
					<label for="" class="control-label">Drawing</label>
					<%= f.collection_select(:spool, @sheets, :spool, :drawing, { prompt: true} , :class => "form-control") %>
				</div>
			</div>
			<div class="modal-footer">
				<%= f.submit 'Save', class: 'btn btn-primary' %>
			</div>

		<% end %>
    </div>
</div>

<script>

 $(document).ready(function(){

 	var requiredFields = ['material_designation', 'material_spool'];
	
	$(".edit_material").submit(function() {
        if (validateform()) {
          return true;
        } else { return false; } 
    });

    function validateform() {
      var bValid = true;      
      jQuery.each ( requiredFields, function (i, val) {
        if ($("#" + val).prop('type') == "text" || $("#" + val).prop('type') == "textarea") {
          if ($("#" + val).val() == "") {
            $("#" + val + "Div").addClass("has-error");
            bValid = false;
           } else { 
            $("#" + val + "Div").removeClass("has-error");
          };
        } else if ($("#" + val).prop('type') == "checkbox") {
          if ($("#" + val).prop("checked") == false) {
            $("#" + val + "Div").addClass("has-error");
            bValid = false;
           } else { 
            $("#" + val + "Div").removeClass("has-error");
          };
        } else if ($("#" + val).prop('type') == "select-one") {
          if ($("#" + val).val() == "") {
            $("#" + val + "Div").addClass("has-error");
            bValid = false;
           } else { 
            $("#" + val + "Div").removeClass("has-error");
          };
        };
      });

      return bValid;
    };

});

</script>

app/views/spools/_new.html.erb
<div class="modal-dialog modal-sm">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add New Spool</h4>
      </div>
      <%= form_for @material, url: requisition_spools_path(@isometric_number), method: :post, remote: true do |f| %>
			<div class="modal-body">				
				<div class="form-group" id="material_designationDiv">
					<label for="" class="control-label">Description</label>
					<%= f.text_field :designation, class: 'form-control' %>
				</div>
				<div class="form-group" id="material_spoolDiv">
					<label for="" class="control-label">Drawing</label>
					<%= f.collection_select(:spool, @sheets, :spool, :drawing, { prompt: true} , :class => "form-control") %>
				</div>
			</div>
			<div class="modal-footer">
				<%= f.submit 'Add', class: 'btn btn-primary' %>
			</div>

		<% end %>
    </div>
</div>

<script>

 $(document).ready(function(){

 	var requiredFields = ['material_designation', 'material_spool'];
	
	$(".new_material").submit(function() {
        if (validateform()) {
          return true;
        } else { return false; } 
    });

    function validateform() {
      var bValid = true;      
      jQuery.each ( requiredFields, function (i, val) {
        if ($("#" + val).prop('type') == "text" || $("#" + val).prop('type') == "textarea") {
          if ($("#" + val).val() == "") {
            $("#" + val + "Div").addClass("has-error");
            bValid = false;
           } else { 
            $("#" + val + "Div").removeClass("has-error");
          };
        } else if ($("#" + val).prop('type') == "checkbox") {
          if ($("#" + val).prop("checked") == false) {
            $("#" + val + "Div").addClass("has-error");
            bValid = false;
           } else { 
            $("#" + val + "Div").removeClass("has-error");
          };
        } else if ($("#" + val).prop('type') == "select-one") {
          if ($("#" + val).val() == "") {
            $("#" + val + "Div").addClass("has-error");
            bValid = false;
           } else { 
            $("#" + val + "Div").removeClass("has-error");
          };
        };
      });

      return bValid;
    };

});

</script>

app/views/spools/_save.html.erb
$("ul.errors").html("")
<% if @material.errors.any? %>
  <% @material.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $("#materiallist").html("<%= escape_javascript(render 'requisitions/materials') %>")
  $("#spool-modal").modal("hide")
<% end %>

app/views/spools/create.js.erb
<%= render "save" %>

app/views/spools/delete.js.erb
$("#spool-modal").html("<%= escape_javascript(render 'delete') %>")
$("#spool-modal").modal("show")

app/views/spools/destroy.js.erb
<%= render "save" %>

app/views/spools/edit.js.erb
$("#spool-modal").html("<%= escape_javascript(render 'edit') %>")
$("#spool-modal").modal("show")

app/views/spools/new.js.erb
$("#spool-modal").html("<%= escape_javascript(render 'new') %>")
$("#spool-modal").modal("show")

app/views/spools/update.js.erb
<%= render "save" %>