config/routes.rb
Rails.application.routes.draw do
  root 'dashboard#index'

  get 'dashboard/index'
  get 'requisitions/print'

  get 'requisitions/get_iso_list'

  resources :requisitions do
    resources :spools do
      get 'delete'
    end
  end
  

  resources :settings #, only: [:index, :update, :create]
  resources :rules
 

end

app/models/rule.rb
class Rule < ActiveRecord::Base
	belongs_to :type
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
	def index
		@rules = Rule.all
	end

	def new
		@rule = Rule.new
		
		# If description passed, populate it. If not, stays blank.
		@rule.search_text = params[:desc]
		@types = Type.all
	end

	def create
		@rule = Rule.create(rule_params)
		@rules = Rule.all
	end

	def edit
		@rule = Rule.find(params[:id])
		@types = Type.all
	end

	def update
		@rule = Rule.find(params[:id])
		@rule.update_attributes(rule_params)
		@rules = Rule.all
	end

	private
		def rule_params
			params.require(:rule).permit(:display_text, :search_text, :type_id)
		end
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/_edit.html.erb
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Edit Rule</h4>
      </div>
      <%= render "form" %>
    </div>
</div>

app/views/rules/_form.html.erb
<%= form_for @rule, remote: true do |f| %>
	<div class="modal-body">
		<div class="row">
			<div class="col-sm-12">
				<div class="form-group">
					<label for="">Search Text</label>
					<%= f.text_field :search_text, class: 'form-control' %>
				</div>
			</div>
			<div class="col-sm-12">
				<div class="form-group">
					<label for="">Description Builder</label>
					<%= f.text_field :display_text, class: 'form-control' %>
				</div>
			</div>
			<div class="col-sm-6">
				<div class="form-group">
					<label for="">Component Type</label>
					<%= f.collection_select(:type_id, @types, :id, :name, {prompt: true}, class: 'form-control') %>
				</div>
			</div>
			<!-- <div class="col-sm-12">
				<div class="form-group">
					<label for="">What it's going to look like</label>
					<p class="form-control-static">100,0 Bolt Up</p>
				</div>
			</div> -->
		</div>
	</div>
	<div class="modal-footer">
        <%= f.submit 'Save Rule', class: 'btn btn-primary' %>
    </div>
<% end %>

app/views/rules/_index.html.erb
<% @rules.each do |r| %>
<tr>
	<td><%= r.search_text %></td>
	<td><%= r.display_text %></td>
	<td><%= r.type.present? ? r.type.name : '' %></td>
	<td>
		<%= link_to 'Edit', edit_rule_path(r), remote: true, class: "btn btn-primary btn-xs" %>
		<%#= link_to 'Delete', admin_job_delete_path(j), remote: true, class: "btn btn-danger btn-xs" %>
	</td>
</tr>
<% end %>

app/views/rules/_new.html.erb
<div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="myModalLabel">Add New Rule</h4>
      </div>
      <%= render "form" %>
    </div>
</div>

app/views/rules/_save.js.erb
$("ul.errors").html("")
<% if @rule.errors.any? %>
  <% @rule.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $("#ruleslist").html("<%= escape_javascript(render 'index') %>")
  $("#rule-modal").modal("hide")
<% end %>

app/views/rules/create.js.erb
<%= render 'save' %>

app/views/rules/edit.js.erb
$("#rule-modal").html("<%= escape_javascript(render 'edit') %>")
$("#rule-modal").modal("show")

app/views/rules/index.html.erb
<div class="container">
	<div class="col-sm-12">
		<div class="form-group clearfix">
			<%= link_to 'New Rule', new_rule_path, remote: true, class: "btn btn-primary pull-right" %>
		</div>
	</div>
	<div class="col-sm-12">
		<div class="panel panel-default">
			<div class="panel-heading">
				<b>Rules</b>
			</div>
			<div class="panel-body">
				<table class="table table-hover">
					<thead>
					  	<tr>
					  		<th>Rule</th>
					  		<th>Definition</th>
					  		<th>Type</th>
					  		<th>Actions</th>
					  	</tr>
					</thead>
					<tbody id="ruleslist">
					  	<%= render "index" %>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>

<div id="rule-modal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true"></div>

app/views/rules/new.js.erb
$("#rule-modal").html("<%= escape_javascript(render 'new') %>")
$("#rule-modal").modal("show")

app/views/rules/update.js.erb
<%= render "save" %>